#pragma once
#include <atomic>
#include <chrono>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <thread>
#include "chess.hpp"
#include "search.hpp"
void uci_loop();
