name: Fastchess SPRT Test (Linux)

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: "Base branch, tag, or commit"
        required: false
        default: "test_chesslib"
      rounds:
        description: "Max rounds for SPRT"
        required: false
        default: "6000"
      tc:
        description: "Time control (e.g. 60+0.6 or 10+0.1)"
        required: false
        default: "60+0.6"
      elo0:
        description: "elo0"
        required: false
        default: "0.5"
      elo1:
        description: "elo1"
        required: false
        default: "2.5"
      output_exec:
        description: "Executable output file name"
        required: false
        default: "engine"

jobs:

  build-new:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: new
          persist-credentials: false

      - name: Install deps
        run: sudo apt update && sudo apt install -y build-essential cmake

      - name: Build new engine
        run: |
          cd new
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Upload new engine
        uses: actions/upload-artifact@v4
        with:
          name: new-engine
          path: new/build/engine


  build-base:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_ref }}
          path: base
          persist-credentials: false

      - name: Install deps
        run: sudo apt update && sudo apt install -y build-essential cmake

      - name: Build base engine
        run: |
          cd base
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Upload base engine
        uses: actions/upload-artifact@v4
        with:
          name: base-engine
          path: base/build/${{ github.event.inputs.output_exec }}


  test:
    runs-on: ubuntu-latest
    needs: [build-new, build-base]

    steps:
      - name: Download engines
        uses: actions/download-artifact@v4

      - name: Install tools
        env:
          OUTPUT_EXEC: ${{ github.event.inputs.output_exec }}
        run: |
          sudo apt update
          sudo apt install -y wget unzip

          wget https://github.com/Disservin/fastchess/releases/download/v1.8.0-alpha/fastchess-linux-x86-64.tar
          tar -xf fastchess-linux-x86-64.tar
          chmod +x fastchess-linux-x86-64/fastchess
          mv fastchess-linux-x86-64/fastchess fastchess

          wget https://github.com/official-stockfish/books/raw/refs/heads/master/UHO_Lichess_4852_v1.epd.zip
          unzip UHO_Lichess_4852_v1.epd.zip

          wget https://github.com/michiguel/Ordo/releases/download/1.0/ordo-linux64
          chmod +x ordo-linux64

          chmod +x new-engine/engine
          chmod +x base-engine/$OUTPUT_EXEC

      - name: Run fastchess
        env:
          ELO0: ${{ github.event.inputs.elo0 }}
          ELO1: ${{ github.event.inputs.elo1 }}
          TC: ${{ github.event.inputs.tc }}
          OUTPUT_EXEC: ${{ github.event.inputs.output_exec }}
          ROUNDS: ${{ github.event.inputs.rounds }}
        run: |
          ./fastchess -recover \
             -engine cmd=new-engine/engine name=new \
             -engine cmd=base-engine/$OUTPUT_EXEC name=base \
             -openings file=UHO_Lichess_4852_v1.epd format=epd order=random \
             -each tc=$TC \
             -rounds $ROUNDS \
             -concurrency $(nproc) \
             -pgnout notation=san nodes=true file=games.pgn \
             -sprt elo0=$ELO0 elo1=$ELO1 alpha=0.05 beta=0.05 | tee results.txt
          ./ordo-linux64 -o ratings.txt -- games.pgn
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            games.pgn
            ratings.txt
            results.txt
