name: Fastchess SPRT Test (Linux)

on:
  workflow_dispatch:

jobs:
  fastchess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main engine
        uses: actions/checkout@v4
        with:
          path: test_chesslib

      - name: Checkout HandcraftedEngine branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: HandcraftedEngine
          path: cppchess_engine

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake wget unzip

      - name: Download fastchess
        run: |
          wget https://github.com/Disservin/fastchess/releases/download/v1.8.0-alpha/fastchess-linux-x86-64.tar
          tar -xf fastchess-linux-x86-64.tar
          cp fastchess-linux-x86-64/fastchess .
          chmod +x fastchess

      - name: Download UHO openings
        run: |
          wget https://github.com/official-stockfish/books/raw/refs/heads/master/UHO_Lichess_4852_v1.epd.zip
          unzip UHO_Lichess_4852_v1.epd.zip

      - name: Build new engine
        run: |
          cd test_chesslib
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Build base engine (HandcraftedEngine)
        run: |
          cd cppchess_engine
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Run fastchess SPRT
        run: |
          ./fastchess -recover \
            -engine cmd=test_chesslib/build/engine name=new \
            -engine cmd=cppchess_engine/build/chess_engine name=base \
            -openings file=UHO_Lichess_4852_v1.epd format=epd order=random \
            -each tc=10+0.5 \
            -rounds 6000 \
            -concurrency $(nproc) \
            -pgnout notation=san nodes=true file=games1.pgn \
            -sprt elo0=0 elo1=2 alpha=0.05 beta=0.05

      - name: Upload PGN
        uses: actions/upload-artifact@v4
        with:
          name: games
          path: games1.pgn
