name: OpenBench Worker

on:
  workflow_dispatch:

jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenBench client
        uses: actions/checkout@v4
        with:
          repository: andygrant/OpenBench

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip make g++
      # gh: ignore leak data reason: locally hosted server
      - name: Run worker
        env:
          OPENBENCH_URL: ${{ secrets.OPENBENCH_URL }}
        run: |
          python Client/Client.py --server ${OPENBENCH_URL} --username=user0 --password=winapiadmin