name: run SPSA (see gist)

on:
  workflow_dispatch:
    inputs:
      output_exec:
        description: "Executable output file name"
        required: false
        default: "engine"
jobs:
  worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          wget https://github.com/official-stockfish/books/raw/refs/heads/master/UHO_Lichess_4852_v1.epd.zip
          unzip UHO_Lichess_4852_v1.epd.zip
          wget https://github.com/Disservin/fastchess/releases/download/v1.8.0-alpha/fastchess-linux-x86-64.tar
          tar -xf fastchess-linux-x86-64.tar
          chmod +x fastchess-linux-x86-64/fastchess
          mv fastchess-linux-x86-64/fastchess fastchess
      - name: Build engine
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . -j$(nproc)
      - name: Tune engine
        run: |
          python spsa.py --iters 160 --pairs 30 --engine build/engine --workers $(nproc) --stable_offset 2000
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spsa-results
          path: |
            ./Weights.h
            games*.pgn
            games*.epd
          compression-level: 9
